# 1.3.1

In [10]:
import numpy as np

a = np.zeros(64).reshape(8,8)

for i in range(8):
  for j in range(8):
      if (i+j) % 2 != 0:
        a[i][j] = 1

print(a)





[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 1.3.2

In [33]:
import numpy as np

array = np.array([np.arange(5) for i in range(5)])
print(array)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3

In [44]:
import numpy as np

array_zn = np.random.random((3,3,3))

print(array_zn)


[[[0.14168426 0.25448278 0.4192    ]
  [0.67282278 0.70327945 0.77767553]
  [0.22109245 0.32971984 0.50482451]]

 [[0.18180611 0.17586146 0.44453223]
  [0.37569013 0.63990452 0.41285635]
  [0.44615687 0.44518809 0.7630045 ]]

 [[0.57607841 0.13354179 0.1391907 ]
  [0.72866933 0.33706695 0.97902668]
  [0.03224253 0.76072572 0.04266627]]]


# 1.3.4

In [51]:
import numpy as np

array = np.array([1, np.array(0), 1])
print(array)

[1 0 1]


# 1.3.5

In [69]:
import numpy as np
import random as r

a =  np.array([r.randint(0, 50) for i in range(5)])
for i in range(len(a)):
  a = np.sort(a, reversed)
print(a)

TypeError: 'type' object cannot be interpreted as an integer

# 1.3.6

# 2.3.1

# 2.3.2

# 2.3.3

# 3.3.2